// <auto-generated>
// Do not edit. Regenerate via Tools/Audio/Refresh Audio Events.

using FMODUnity;

public static class AudioEvents
{
    public static readonly EventReference Test = new EventReference
    {
#if UNITY_EDITOR
        Path = "event:/Test",
#endif
        Guid = FMOD.GUID.Parse("{d168b65e-e6c9-4a1c-94ac-3e9b802d9f3e}")
    };
}

