using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using FMODUnity;
using UnityEditor;
using UnityEngine;

public static class AudioEventsGenerator
{
    const string MenuPath = "Tools/Audio/Refresh Audio Events";
    const string OutputAssetPath = "Assets/Audio/AudioEvents.cs";

    static readonly HashSet<string> Keywords = new HashSet<string>
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while", "add", "alias", "ascending", "async", "await", "by",
        "descending", "dynamic", "equals", "from", "get", "global", "group", "init", "into",
        "join", "let", "nameof", "nint", "notnull", "nuint", "on", "or", "orderby", "partial",
        "record", "remove", "required", "scoped", "select", "set", "unmanaged", "value", "var",
        "when", "where", "with", "yield"
    };

    [MenuItem(MenuPath)]
    public static void RefreshAudioEvents()
    {
        var records = new List<(string path, string guid)>();
        foreach (EditorEventRef editorEvent in EventManager.Events)
        {
            if (editorEvent == null || string.IsNullOrEmpty(editorEvent.Path))
                continue;

            records.Add((editorEvent.Path, editorEvent.Guid.ToString()));
        }

        string source = BuildSource(records);
        string absolutePath = Path.Combine(Directory.GetParent(Application.dataPath).FullName, OutputAssetPath);

        Directory.CreateDirectory(Path.GetDirectoryName(absolutePath));

        if (File.Exists(absolutePath) && File.ReadAllText(absolutePath) == source)
        {
            Debug.Log($"Audio events are already up to date ({records.Count} events).");
            return;
        }

        File.WriteAllText(absolutePath, source);
        AssetDatabase.ImportAsset(OutputAssetPath);
        Debug.Log($"Wrote {records.Count} audio events to {OutputAssetPath}.");
    }

    public static string BuildSource(IEnumerable<(string path, string guid)> events)
    {
        var byPath = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var record in events)
        {
            if (string.IsNullOrEmpty(record.path))
                continue;

            byPath[record.path] = record.guid ?? string.Empty;
        }

        var root = new FolderNode(string.Empty);
        foreach (var pair in byPath.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            string[] segments = SplitPath(pair.Key);
            if (segments.Length == 0)
                continue;

            FolderNode node = root;
            for (int i = 0; i < segments.Length - 1; i++)
            {
                string raw = segments[i];
                if (!node.Children.TryGetValue(raw, out FolderNode child))
                {
                    child = new FolderNode(raw);
                    node.Children.Add(raw, child);
                }

                node = child;
            }

            node.Leaves.Add(new Leaf(segments[segments.Length - 1], pair.Key, pair.Value));
        }

        AssignIdentifiers(root);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Do not edit. Regenerate via Tools/Audio/Refresh Audio Events.");
        sb.AppendLine();
        sb.AppendLine("using FMODUnity;");
        sb.AppendLine();
        sb.AppendLine("public static class AudioEvents");
        sb.AppendLine("{");
        AppendMembers(sb, root, 1);
        sb.AppendLine("}");
        sb.AppendLine();
        return sb.ToString();
    }

    static string[] SplitPath(string path)
    {
        string remainder = path;
        if (remainder.StartsWith("event:/", StringComparison.OrdinalIgnoreCase))
            remainder = remainder.Substring("event:/".Length);
        else if (remainder.StartsWith("snapshot:/", StringComparison.OrdinalIgnoreCase))
            remainder = remainder.Substring("snapshot:/".Length);
        else
        {
            int scheme = remainder.IndexOf(":/", StringComparison.Ordinal);
            if (scheme >= 0)
                remainder = remainder.Substring(scheme + 2);
        }

        if (remainder.Length == 0)
            return Array.Empty<string>();

        return remainder.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
    }

    static void AssignIdentifiers(FolderNode node)
    {
        var used = new HashSet<string>();
        var children = node.Children.Values.OrderBy(child => child.RawName, StringComparer.Ordinal).ToList();
        foreach (FolderNode child in children)
            child.Identifier = Allocate(Sanitize(child.RawName), used);

        var folderNames = new HashSet<string>(children.Select(child => child.Identifier));
        foreach (Leaf leaf in node.Leaves.OrderBy(leaf => leaf.Path, StringComparer.Ordinal))
        {
            string name = Sanitize(leaf.RawName);
            if (folderNames.Contains(name))
                name += "_Event";

            leaf.Identifier = Allocate(name, used);
        }

        foreach (FolderNode child in children)
            AssignIdentifiers(child);
    }

    static string Allocate(string baseName, HashSet<string> used)
    {
        string candidate = baseName;
        int suffix = 2;
        while (!used.Add(candidate))
        {
            candidate = baseName + "_" + suffix;
            suffix++;
        }

        return candidate;
    }

    static string Sanitize(string raw)
    {
        var sb = new StringBuilder(raw.Length);
        foreach (char c in raw)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        if (sb.Length == 0)
            sb.Append("Unnamed");

        if (!char.IsLetter(sb[0]) && sb[0] != '_')
            sb.Insert(0, '_');

        string name = sb.ToString();
        if (Keywords.Contains(name))
            name = "_" + name;

        return name;
    }

    static void AppendMembers(StringBuilder sb, FolderNode node, int indent)
    {
        string pad = new string(' ', indent * 4);
        string field = new string(' ', (indent + 1) * 4);
        bool any = false;

        foreach (FolderNode child in node.Children.Values.OrderBy(child => child.Identifier, StringComparer.Ordinal))
        {
            if (any)
                sb.AppendLine();

            any = true;
            sb.Append(pad).Append("public static class ").Append(child.Identifier).AppendLine();
            sb.Append(pad).AppendLine("{");
            AppendMembers(sb, child, indent + 1);
            sb.Append(pad).AppendLine("}");
        }

        foreach (Leaf leaf in node.Leaves.OrderBy(leaf => leaf.Identifier, StringComparer.Ordinal))
        {
            if (any)
                sb.AppendLine();

            any = true;
            sb.Append(pad).Append("public static readonly EventReference ").Append(leaf.Identifier).AppendLine(" = new EventReference");
            sb.Append(pad).AppendLine("{");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.Append(field).Append("Path = \"").Append(Escape(leaf.Path)).AppendLine("\",");
            sb.AppendLine("#endif");
            sb.Append(field).Append("Guid = FMOD.GUID.Parse(\"").Append(Escape(leaf.Guid)).AppendLine("\")");
            sb.Append(pad).AppendLine("};");
        }
    }

    static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }

    sealed class FolderNode
    {
        public FolderNode(string rawName)
        {
            RawName = rawName;
        }

        public string RawName { get; }
        public string Identifier;
        public Dictionary<string, FolderNode> Children { get; } = new Dictionary<string, FolderNode>();
        public List<Leaf> Leaves { get; } = new List<Leaf>();
    }

    sealed class Leaf
    {
        public Leaf(string rawName, string path, string guid)
        {
            RawName = rawName;
            Path = path;
            Guid = guid;
        }

        public string RawName { get; }
        public string Path { get; }
        public string Guid { get; }
        public string Identifier;
    }
}
